Tests Daniel Berrío Barrera
DanielBerrioB/pruebasTaller pull request #2
Opened 2020-10-02 00:01 UTC by DanielBerrioB

Se agregan 3 tests para probar la funcion_1:

Test 1: Se comprueba el caso ideal con un valor que se encuentre dentro del dominio de la funcion.
Test 2: Se comprueba que la función soporte el caso cuando el valor sea Infinity, lo que indica que está fuera del dominio de la función.
Test 3: Se comprueba que no se hagan otras operaciones si el usuario no ha ingresado ninguna opción válida al inicio de la función main. Esta retorna el mensaje de "Opción inválida".

2020-10-02 19:30 UTC, jose0044 commented on index.js
> +  return 1 / (num - Math.pow(num, 2) + 2);
Que sucede si num es 0 o si es negativo? Puede afectar el codigo?

2020-10-02 19:31 UTC, jose0044 requested changes
Revisar el comentario hecho

2020-10-04 02:03 UTC, DanielBerrioB commented on index.js
> +  return 1 / (num - Math.pow(num, 2) + 2);
Listo. Se agregaron nuevos tests cubriendo ese tipo de casos y además se cambió el nombre del algunas funciones.

2020-10-04 16:18 UTC, jose0044 approved these changes

2020-10-05 15:47 UTC, celciusjj commented
¡Todo ok!

2020-10-05 15:50 UTC, merged